#!/bin/bash
#This is a Caldine Fashion Script to welcome customers on the online app
#Please only run this script if you have sudo previllages
#Please sure before editing this code you are in the sudoers list 

echo "Welcome To Caldine Fashion"
echo "Pleasee enter your department"
read department
echo "please enter your batch number"
read batch number
echo "Please Enter Your username"
read username
echo "Please enter Your Password"
read Password
if (( $Password == 12345 ))
then 
echo "You have succesfully login on the" `date`
else
echo "you entered the wrong password"
fi 

